# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2aeef01e716df073d7052a92bfcf8ab6"
name = "product-group-bundler"
application_url = "https://bundler.icarsoft-france.fr"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_cart_transforms,write_cart_transforms"

[auth]
redirect_urls = [ "https://bundler.icarsoft-france.fr/api/auth" ]

[product.metafields.app.bundle_groups]
type = "json"
name = "Bundle Groups"
description = "Configuration for product bundle groups (accessories, tools, etc.)"

  [product.metafields.app.bundle_groups.access]
  admin = "merchant_read"
  storefront = "public_read"
