api_version = "2026-04"

[[extensions]]
type = "function"
name = "Bundle Discount"
handle = "bundle-discount"
description = "Applies bundle discount to grouped product lines in the cart"
uid = "880efb62-6c5e-ad93-d249-9913aad3d9cb8bb0dbab"

  [extensions.build]
  path = "dist/index.wasm"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/input.graphql"
  export = "run"

  [extensions.ui.paths]
  create = "/app/bundle-settings"
  details = "/app/bundle-settings"
